export enum TaskLabel {
  MEETING = 'MEETING',
  DEFECTS_OR_BUGS = 'DEFECTS_OR_BUGS',
  SALES_SUPPORT = 'SALES_SUPPORT',
  RELEASE_MANAGEMENT = 'RELEASE_MANAGEMENT',
  JIRA_ESCALATED = 'JIRA_ESCALATED',
}
